version: '3.9'

services:

  flask-app:

    build: .

    ports:
      - "5000:5000"

    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: notes_app
      SECRET_KEY: mysecretkey

    depends_on:
      - mysql-db

  mysql-db:

    image: mysql:8.0

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: notes_app

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql


volumes:

  mysql_data: